### ISSUE TITLE
Add Automatic-Module-Name to MANIFEST.MF

### ISSUE THREAD

**Issue by AndreasWBartels** [jeffhain/jafama#6]
Please add the property Automatic-Module-Name to the MANIFEST.MF file. For better support in projects using the Java Platform Module System (JPMS).

**Comment by jeffhain** [comment]
Hello.

Just learned about this attribute with your message.
Does this manifest look good to you, or did I miss something?
(I might piggyback a few modifs but nothing functional, so for the new version I'll only increment the "patch" digit.)

Manifest-Version: 1.0
Automatic-Module-Name: net.jafama
Implementation-Version: 2.3.2

**Comment by AndreasWBartels** [comment]
That's looks good 

Thanks

**Comment by jeffhain** [comment]
Uploaded 2.3.2 to sonatype, can see it here
https://oss.sonatype.org/#nexus-search;quick~jafama
but it's not visible in
https://mvnrepository.com/artifact/net.jafama/jafama
yet.

Hope it works ;)
